version: "3.8"
services:
  app:
    container_name: atacado-hub-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
      npm install && 
      npm run start:dev
      "
    networks:
      - atacado-hub-network
      
  db:
    image: postgres:14-alpine
    container_name: atacado-hub-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atacado-hub
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - atacado-hub-network

volumes:
  atacado-hub-data:

networks:
  atacado-hub-network:
    driver: bridge